In [1]:
import json
from pprint import pprint

In [17]:
data_2015 = json.load(open('ClimaMensual2015.txt'))
data_2016 = json.load(open('ClimaMensual2016.txt'))
data_2017 = json.load(open('ClimaMensual2017.txt'))

In [4]:
import pandas as pd

In [18]:
clima_2015 = pd.DataFrame(data_2015)
clima_2016 = pd.DataFrame(data_2016)
clima_2017 = pd.DataFrame(data_2017)

In [16]:
clima_2015.head()

,e,evap,fecha,glo,hr,indicativo,inso,n_cub,n_des,n_fog,...,tm_max,tm_mes,tm_min,ts_10,ts_20,ts_50,ts_min,w_med,w_racha,w_rec
0,71.0,852.0,2015-1,32451.0,53.0,7178I,7.7,2.0,13.0,0.0,...,18.3,11.1,3.8,10.0,9.6,10.8,9.2,9.0,30/23.6(31),199.0
1,83.0,1023.0,2015-2,33292.0,57.0,7178I,6.5,5.0,2.0,0.0,...,17.4,12.0,6.6,12.2,11.6,12.1,14.4,11.0,30/20.0(04),271.0
2,107.0,1069.0,2015-3,51608.0,60.0,7178I,7.6,6.0,7.0,2.0,...,22.1,15.5,8.9,17.6,16.5,16.3,14.2,10.0,08/16.7(19),213.0
3,124.0,1259.0,2015-4,59737.0,59.0,7178I,7.6,9.0,1.0,0.0,...,23.5,17.6,11.7,20.3,19.4,NaN,15.6,11.0,25/14.2(26),225.0
4,156.0,2087.0,2015-5,80152.0,52.0,7178I,10.6,2.0,10.0,0.0,...,30.0,22.9,15.8,27.3,25.9,NaN,18.8,12.0,05/13.3(19),223.0

In [19]:
clima_2016.head()

,e,evap,fecha,glo,hr,indicativo,inso,n_cub,n_des,n_fog,...,ta_min,ti_max,tm_max,tm_mes,tm_min,ts_20,ts_min,w_med,w_racha,w_rec
0,96.0,802.0,2016-1,27311.0,61.0,7178I,6.2,NaN,NaN,0.0,...,1.7(17),13.4,19.5,13.7,7.9,13.2,17.9,8.0,34/15.0(16),174.0
1,86.0,1093.0,2016-2,34866.0,52.0,7178I,6.7,NaN,NaN,0.0,...,1.0(17),15.1,20.1,14.3,8.4,14.4,16.2,11.0,27/22.5(14),252.0
2,83.0,1210.0,2016-3,54091.0,49.0,7178I,8.7,NaN,NaN,0.0,...,4.2(09),13.5,21.5,14.9,8.2,16.9,12.4,10.0,30/20.0(10),221.0
3,111.0,1337.0,2016-4,63125.0,52.0,7178I,9.0,6.0,3.0,0.0,...,6.2(02),15.4,24.4,18.2,12.0,21.8,16.9,10.0,05/16.9(30),214.0
4,126.0,1779.0,2016-5,77671.0,49.0,7178I,10.4,2.0,7.0,0.0,...,8.6(02),20.9,27.3,20.8,14.2,25.2,18.4,12.0,30/17.5(13),243.0

In [32]:
clima_2017.dtypes

e             object
evap          object
fecha         object
glo           object
hr            object
indicativo    object
inso          object
n_cub         object
n_des         object
n_fog         object
n_gra         object
n_llu         object
n_nie         object
n_nub         object
n_tor         object
np_001        object
np_010        object
np_100        object
np_300        object
nt_00         object
nt_30         object
nv_0050       object
nv_0100       object
nv_1000       object
nw_55         object
nw_91         object
p_max         object
p_mes         object
p_sol         object
q_mar         object
q_max         object
q_med         object
q_min         object
ta_max        object
ta_min        object
ti_max        object
tm_max        object
tm_mes        object
tm_min        object
ts_20         object
ts_min        object
w_med         object
w_racha       object
w_rec         object
dtype: object

In [40]:
frames = [clima_2015, clima_2016, clima_2017]
Clima_mensual = pd.concat(frames,ignore_index=True)

In [50]:
Clima_mensual.to_csv('ClimaMensual.txt',sep='|')

In [21]:
metadatos = json.load(open('Metadatos clima mensual.txt'))

In [27]:
metados_mensual = pd.DataFrame(metadatos['campos'])

In [33]:
metados_mensual

,descripcion,id,requerido,tipo_datos,unidad
0,ano y mes (AAAA-X) donde X es un nÃºmero de 1 a...,fecha,True,string,NaN
1,indicativo climatolÃ³gico,indicativo,True,string,NaN
2,nombre (ubicaciÃ³n) de la estaciÃ³n,nombre,True,string,NaN
3,provincia de la estaciÃ³n,provincia,True,string,NaN
4,altitud de la estaciÃ³n en m sobre el nivel del...,altitud,True,string,m
5,Temperatura media mensual/anual (grados celsius),tm_mes,False,string,grados celsius
6,Temperatura media mensual/anual de las mÃ¡ximas...,tm_max,False,string,grados celsius
7,Temperatura media mensual/anual de las mÃ­nimas...,tm_min,False,string,grados celsius
8,Temperatura mÃ¡xima absoluta del mes/aÃ±o y fech...,ta_max,False,string,grados celsius
9,Temperatura mÃ­nima absoluta del mes/aÃ±o y fech...,ta_min,False,string,grados celsius
10,Temperatura mÃ­nima mas alta del mes/aÃ±o (grado...,ts_min,False,string,grados celsius
11,Temperatura mÃ¡xima mas baja del mes/aÃ±o (grado...,ti_max,False,string,grados celsius
12,NÂº de dÃ­as de temperatura mÃ¡xima mayor o igual...,nt_30,False,string,nÃºmero de dÃ­as
13,NÂº de dÃ­as de temperatura mÃ­nima menor o igual...,nt_00,False,nÃºmero de dÃ­as,grados celsius
14,PrecipitaciÃ³n total mensual/anual (mm),p_mes,False,string,mm
15,PrecipitaciÃ³n mÃ¡xima diaria (mm) del mes/aÃ±o y...,p_max,False,string,mm (dia o fecha del aÃ±o)
16,"NÂº de dÃ­as de precipitaciÃ³n apreciable (>= 0,1...",np_001,False,string,nÃºmero de dÃ­as
17,NÂº de dÃ­as de precipitaciÃ³n mayor o igual que ...,np_010,False,string,nÃºmero de dÃ­as
18,NÂº de dÃ­as de precipitaciÃ³n mayor o igual que ...,np_100,False,string,nÃºmero de dÃ­as
19,NÂº de dÃ­as de precipitaciÃ³n mayor o igual que ...,np_300,False,string,nÃºmero de dÃ­as
20,Humedad relativa media mensual/anual (%),hr,False,string,%
21,TensiÃ³n de vapor media mensual/anual (dÃ©cimas ...,e,False,string,dÃ©cimas de hPa
22,NÂº de dÃ­as de lluvia en el mes/aÃ±o,n_llu,False,string,nÃºmero de dÃ­as
23,NÂº de dÃ­as de nieve en el mes/aÃ±o,n_nie,False,string,nÃºmero de dÃ­as
24,NÂº de dÃ­as de granizo en el mes/aÃ±o,n_gra,False,string,nÃºmero de dÃ­as
25,NÂº de dÃ­as de tormenta en el mes/aÃ±o,n_tor,False,string,nÃºmero de dÃ­as
26,NÂº de dÃ­as de niebla en el mes/aÃ±o,n_fog,False,string,nÃºmero de dÃ­as
27,NÂº de dÃ­as despejados en el mes/aÃ±o,n_des,False,string,nÃºmero de dÃ­as
28,NÂº de dÃ­as nubosos en el mes/aÃ±o,n_nub,False,string,nÃºmero de dÃ­as
29,NÂº de dÃ­as cubiertos en el mes/aÃ±o,n_cub,False,string,nÃºmero de dÃ­as
30,Media mensual/anual de la insolaciÃ³n diaria (h...,inso,False,string,nÃºmero de dÃ­as
31,Porcentaje medio mensual de la insolaciÃ³n diar...,p_sol,False,string,%
32,RadiaciÃ³n global mensual/anual (decenas de Kj*...,glo,False,string,Kj.m2
33,EvaporaciÃ³n total mensual/anual (dÃ©cimas de mm),evap,False,string,dÃ©cimas de mm
34,Recorrido medio diario (de 07 a 07 UTC) del me...,w_rec,False,string,Km
35,"DirecciÃ³n (decenas de grado), Velocidad (m/sg)...",w_racha,False,string,decenas de grado/ m/sg /fecha
36,NÂº de dÃ­as de velocidad del viento mayor o igu...,nw_55,False,string,nÃºmero de dÃ­as
37,NÂº de dÃ­as de velocidad del viento mayor o igu...,nw_91,False,string,nÃºmero de dÃ­as
38,Velocidad media mensual elaborada a partir de ...,w_med,False,string,Km/h
39,NÂº de dÃ­as de velocidad del viento mayor o igu...,nw_55,False,string,nÃºmero de dÃ­as
40,PresiÃ³n media mensual/anual al nivel de la est...,q_med,False,string,hPa
41,PresiÃ³n mÃ¡xima absoluta mensual/anual y fecha ...,q_max,False,string,hPa
42,PresiÃ³n mÃ¡xima mÃ­nima mensual/anual y fecha (hPa),q_min,False,string,hPa
43,PresiÃ³n media mensual/anual al nivel del mar (...,q_mar,False,string,hPa
44,Temperatura media mensual/anual a 10 cm de pro...,ts_10,False,string,grados celsius
45,Temperatura media mensual/anual a 20 cm (grado...,ts_20,False,string,grados celsius
46,Temperatura media mensual/anual a 20 cm (grado...,ts_50,False,string,grados celsius
47,NÂº de dÃ­as con visibilidad inferior a 50 m. en...,nv_0050,False,string,nÃºmero de dÃ­as
48,NÂº de dÃ­as con visibilidad superior o igual a ...,nv_0100,False,string,nÃºmero de dÃ­as
49,NÂº de dÃ­as con visibilidad superior o igual a ...,nv_1000,False,string,nÃºmero de dÃ­as

In [49]:
metados_mensual.to_csv('MetadatosMensual.txt',sep='|')

In [51]:
Clima_Oct_2015 = json.load(open('Climadiariooct2015.txt'))

In [52]:
clima_diario_Oct_2015 = pd.DataFrame(Clima_Oct_2015)

In [53]:
clima_diario_Oct_2015

,altitud,dir,fecha,horaPresMax,horaPresMin,horaracha,horatmax,horatmin,indicativo,nombre,prec,presMax,presMin,provincia,racha,sol,tmax,tmed,tmin,velmedia
0,61,22,2015-10-01,09,17,16:00,14:20,03:20,7178I,MURCIA,"0,0","1015,5","1011,9",MURCIA,"7,8","10,1","29,1","23,1","17,1","1,7"
1,61,22,2015-10-02,00,16,13:50,13:00,06:00,7178I,MURCIA,"0,0","1012,4","1007,3",MURCIA,"9,4","10,2","30,7","23,2","15,7","1,4"
2,61,99,2015-10-03,24,14,Varias,14:50,06:00,7178I,MURCIA,"0,0","1010,7","1007,3",MURCIA,"4,4","2,2","27,1","22,2","17,2","0,6"
3,61,16,2015-10-04,22,00,15:50,15:30,05:40,7178I,MURCIA,"0,0","1013,3","1010,4",MURCIA,"5,3","7,6","31,1","24,0","17,0","1,4"
4,61,99,2015-10-05,Varias,24,Varias,13:00,04:40,7178I,MURCIA,Ip,"1012,6","1007,5",MURCIA,"10,8","1,8","32,4","26,4","20,4","3,6"
5,61,24,2015-10-06,23,03,15:50,14:30,02:40,7178I,MURCIA,"0,0","1009,3","1005,8",MURCIA,"8,9","9,9","31,0","25,0","19,0","2,5"
6,61,05,2015-10-07,08,14,17:30,13:30,05:10,7178I,MURCIA,"0,0","1010,9","1007,6",MURCIA,"6,7","8,3","28,0","23,1","18,2","2,2"
7,61,08,2015-10-08,21,15,17:00,13:10,04:50,7178I,MURCIA,"0,0","1009,4","1006,8",MURCIA,"12,2","8,2","25,3","21,4","17,4","3,6"
8,61,12,2015-10-09,00,15,16:10,14:20,06:00,7178I,MURCIA,"0,0","1008,7","1004,7",MURCIA,"6,4","8,4","26,9","21,5","16,1","1,4"
9,61,14,2015-10-10,00,17,15:00,14:10,06:10,7178I,MURCIA,"0,0","1006,0","1001,5",MURCIA,"6,9","10,4","28,0","21,4","14,9","1,7"
10,61,24,2015-10-11,00,16,13:00,14:40,02:10,7178I,MURCIA,"0,0","1002,3","998,9",MURCIA,"4,2","7,8","29,4","23,2","17,1","1,4"
11,61,17,2015-10-12,Varias,03,15:30,14:50,05:40,7178I,MURCIA,"0,0","1004,1","1001,2",MURCIA,"6,7","10,1","29,7","23,4","17,2","0,8"
12,61,07,2015-10-13,23,16,20:00,15:30,01:50,7178I,MURCIA,Ip,"1006,0","1002,2",MURCIA,"10,8","6,8","27,8","22,9","18,0","1,9"
13,61,32,2015-10-14,22,Varias,08:30,15:50,23:59,7178I,MURCIA,"0,0","1007,2","1003,3",MURCIA,"8,3","9,0","26,2","21,2","16,2","1,7"
14,61,15,2015-10-15,22,16,16:10,13:50,06:30,7178I,MURCIA,"0,0","1008,2","1005,2",MURCIA,"6,1","10,4","27,8","20,8","13,7","1,7"
15,61,07,2015-10-16,09,16,17:20,12:30,06:10,7178I,MURCIA,"0,0","1009,8","1006,7",MURCIA,"7,2","4,4","25,1","21,1","17,1","1,9"
16,61,07,2015-10-17,09,15,14:30,13:40,Varias,7178I,MURCIA,Ip,"1008,7","1005,0",MURCIA,"8,6","6,8","26,1","21,4","16,6","3,1"
17,61,06,2015-10-18,08,Varias,12:30,14:40,06:50,7178I,MURCIA,"5,8","1007,9","1002,9",MURCIA,"8,1","8,8","26,8","21,2","15,7","2,8"
18,61,36,2015-10-19,22,Varias,02:40,15:00,06:30,7178I,MURCIA,"0,0","1005,0","1001,2",MURCIA,"7,2","9,7","27,6","22,2","16,9","1,4"
19,61,30,2015-10-20,Varias,04,09:50,10:40,Varias,7178I,MURCIA,"7,8","1009,2","1003,9",MURCIA,"5,6","1,6","23,4","20,2","17,0","1,7"
20,61,34,2015-10-21,22,05,13:40,15:10,23:59,7178I,MURCIA,"0,0","1012,5","1008,3",MURCIA,"9,7","7,3","22,8","18,4","13,9","3,6"
21,61,34,2015-10-22,21,14,10:40,15:10,05:50,7178I,MURCIA,"0,0","1014,5","1011,3",MURCIA,"8,6","10,1","25,1","18,0","11,0","3,1"
22,61,05,2015-10-23,09,15,15:20,15:01,06:50,7178I,MURCIA,"0,0","1014,9","1011,5",MURCIA,"6,4","5,9","25,2","18,4","11,5","2,2"
23,61,30,2015-10-24,21,04,07:40,14:30,02:40,7178I,MURCIA,"0,6","1013,6","1010,8",MURCIA,"4,2","0,0","20,3","17,8","15,3","1,4"
24,61,12,2015-10-25,08,24,15:30,Varias,04:20,7178I,MURCIA,"1,2","1013,9","1010,6",MURCIA,"4,7","0,0","21,6","19,2","16,9","1,7"
25,61,06,2015-10-26,00,14,16:10,12:40,06:30,7178I,MURCIA,"0,0","1010,6","1006,1",MURCIA,"5,8","1,0","21,8","19,3","16,8","1,7"
26,61,32,2015-10-27,24,16,20:50,15:30,06:50,7178I,MURCIA,"0,0","1008,5","1004,4",MURCIA,"7,8","6,1","25,6","20,2","14,9","1,1"
27,61,33,2015-10-28,24,01,16:00,15:20,05:40,7178I,MURCIA,"0,0","1013,7","1008,1",MURCIA,"7,5","9,6","24,8","18,2","11,7","1,9"
28,61,24,2015-10-29,Varias,16,10:50,14:00,06:30,7178I,MURCIA,"0,0","1014,9","1010,5",MURCIA,"6,1","9,9","25,0","17,9","10,8","1,7"
29,61,05,2015-10-30,10,Varias,14:30,13:40,06:50,7178I,MURCIA,"0,0","1013,5","1011,3",MURCIA,"6,4","9,9","24,8","19,0","13,1","2,2"
30,61,07,2015-10-31,22,03,14:30,12:30,03:30,7178I,MURCIA,"0,0","1015,6","1011,8",MURCIA,"8,6","5,3","23,3","18,5","13,7","2,8"

In [56]:
Metadatos_diarios = json.load(open('metadatos clima diario.txt'))
Metadatos_clima_diarios = pd.DataFrame(Metadatos_diarios['campos'])

In [57]:
Metadatos_clima_diarios

,descripcion,id,requerido,tipo_datos,unidad
0,fecha del dia (AAAA-MM-DD),fecha,True,string,NaN
1,indicativo climatolÃ³gico,indicativo,True,string,NaN
2,nombre (ubicaciÃ³n) de la estaciÃ³n,nombre,True,string,NaN
3,provincia de la estaciÃ³n,provincia,True,string,NaN
4,altitud de la estaciÃ³n en m sobre el nivel del...,altitud,True,float,m
5,Temperatura media diaria,tmed,False,float,grados celsius
6,PrecipitaciÃ³n diaria de 07 a 07,prec,False,float,mm
7,Temperatura MÃ­nima del dÃ­a,tmin,False,float,ÂºC
8,Hora y minuto de la temperatura mÃ­nima,horatmin,False,string,UTC
9,Temperatura MÃ¡xima del dÃ­a,tmax,False,float,ÂºC
10,Hora y minuto de la temperatura mÃ¡xima,horatmax,False,string,UTC
11,DirecciÃ³n de la racha mÃ¡xima,dir,False,float,decenas de grado
12,Velocidad media del viento,velmedia,False,float,m/s
13,Racha mÃ¡xima del viento,racha,False,float,m/s
14,Hora y minuto de la racha mÃ¡xima,horaracha,False,float,UTC
15,InsolaciÃ³n,sol,False,float,horas
16,PresiÃ³n mÃ¡xima al nivel de referencia de la es...,presmax,False,float,hPa
17,Hora de la presiÃ³n mÃ¡xima (redondeada a la hor...,horapresmax,False,float,hora entera
18,PresiÃ³n mÃ­nima al nivel de referencia de la es...,presmin,False,float,hPa
19,Hora de la presiÃ³n mÃ­nima (redondeada a la hor...,horapresmin,False,float,hora entera

In [186]:
mes = ["oct","nov","dic","ene","feb","marzo","abril","mayo","junio","julio","agosto","sept"]
meses = mes + mes

In [187]:
import numpy as np

In [188]:
x = np.array([2015,2016,2017])
aÃ±os = np.repeat(x, [3,12,9], axis=0)

In [189]:
lista = []
for i in range(24):
    lista.append(("climadiario%s%i.txt" % (meses[i],aÃ±os[i])))

In [190]:
lista

['climadiariooct2015.txt',
 'climadiarionov2015.txt',
 'climadiariodic2015.txt',
 'climadiarioene2016.txt',
 'climadiariofeb2016.txt',
 'climadiariomarzo2016.txt',
 'climadiarioabril2016.txt',
 'climadiariomayo2016.txt',
 'climadiariojunio2016.txt',
 'climadiariojulio2016.txt',
 'climadiarioagosto2016.txt',
 'climadiariosept2016.txt',
 'climadiariooct2016.txt',
 'climadiarionov2016.txt',
 'climadiariodic2016.txt',
 'climadiarioene2017.txt',
 'climadiariofeb2017.txt',
 'climadiariomarzo2017.txt',
 'climadiarioabril2017.txt',
 'climadiariomayo2017.txt',
 'climadiariojunio2017.txt',
 'climadiariojulio2017.txt',
 'climadiarioagosto2017.txt',
 'climadiariosept2017.txt']

In [191]:
nombres = []
for i in range(24):
    nombres.append(("climadiario%s%i" % (meses[i],aÃ±os[i])))

In [192]:
nombres

['climadiariooct2015',
 'climadiarionov2015',
 'climadiariodic2015',
 'climadiarioene2016',
 'climadiariofeb2016',
 'climadiariomarzo2016',
 'climadiarioabril2016',
 'climadiariomayo2016',
 'climadiariojunio2016',
 'climadiariojulio2016',
 'climadiarioagosto2016',
 'climadiariosept2016',
 'climadiariooct2016',
 'climadiarionov2016',
 'climadiariodic2016',
 'climadiarioene2017',
 'climadiariofeb2017',
 'climadiariomarzo2017',
 'climadiarioabril2017',
 'climadiariomayo2017',
 'climadiariojunio2017',
 'climadiariojulio2017',
 'climadiarioagosto2017',
 'climadiariosept2017']

In [193]:
data = []
for i in range(24):
    data.append(json.load(open(lista[i])))

In [194]:
df = pd.DataFrame()

In [195]:
for item in range(len(data)):
    datos = pd.DataFrame(data[item])
    df = df.append(datos,ignore_index=True)

In [196]:
df.to_csv("Clima_diario.txt",sep="|")

In [197]:
metadatos = json.load(open('metadatos clima diario.txt'))

In [198]:
metados_diario = pd.DataFrame(metadatos['campos'])

In [199]:
metados_diario.to_csv('MetadatosDiario.txt',sep='|')